/**
 * Binding for the Rust/WASM kernel twin (`crates/kernel-wasm`).
 *
 * Deliberately hand-written against a raw C ABI rather than generated by
 * wasm-bindgen. The crate is being judged on whether its float operations match
 * the TypeScript kernel's bit-for-bit, and generated glue is code that sits
 * between the two and that nobody reviews. A hundred lines of `DataView` work
 * is a fair price for keeping codegen out of the comparison.
 *
 * Every method here mirrors the signature of its `kernel/` counterpart, so the
 * parity harness can drive both kernels through one interface and know it is
 * comparing like with like.
 *
 * This module lives outside `kernel/` and is not subject to the op whitelist —
 * it performs no generation arithmetic, only marshalling.
 */
import type { FbmParams } from '../kernel/fbm.js';
import type { Direction, FaceUv } from '../kernel/cubesphere.js';
import type { TileGenInput, TileGenOutput } from '../kernel/tilegen.js';

/** ABI revision this binding speaks. Must match `tm_abi_version()` in the crate. */
const EXPECTED_ABI_VERSION = 1;

/** Doubles in the `tm_generate_tile` parameter block; see the Rust doc comment. */
const TILE_PARAM_COUNT = 14;

/**
 * The host's WebAssembly surface, described structurally.
 *
 * `packages/core` compiles against `lib: ["ES2022"]` with no DOM, deliberately:
 * the package must stay consumable from Node scripts and must not acquire an
 * accidental dependency on a browser global. `WebAssembly` and `BufferSource`
 * are declared in `lib.dom.d.ts`, so rather than widen `lib` — which would let
 * `document` and `window` typecheck in headless code — the three members
 * actually used are described here and reached through `globalThis`.
 *
 * Structural typing means a real `WebAssembly.Instance` satisfies
 * `WasmInstanceLike`, so a caller that does have the DOM types can pass one to
 * {@link wrapWasmKernel} unchanged.
 */
interface WasmMemoryLike {
  readonly buffer: ArrayBufferLike;
}

export interface WasmInstanceLike {
  readonly exports: Record<string, unknown>;
}

interface WasmHost {
  instantiate(
    bytes: ArrayBuffer | ArrayBufferView,
    imports: object,
  ): Promise<{ readonly instance: WasmInstanceLike }>;
}

/** Raw exports of the compiled crate. */
interface RawExports {
  readonly memory: WasmMemoryLike;
  readonly tm_abi_version: () => number;
  readonly tm_alloc: (size: number) => number;
  readonly tm_free: (ptr: number, size: number) => void;

  readonly tm_pow2: (x: number) => number;
  readonly tm_pow3: (x: number) => number;
  readonly tm_powi: (x: number, n: number) => number;
  readonly tm_clamp: (x: number, lo: number, hi: number) => number;
  readonly tm_lerp: (a: number, b: number, t: number) => number;
  readonly tm_smoothstep: (t: number) => number;
  readonly tm_smootherstep: (t: number) => number;

  readonly tm_mix32: (x: number) => number;
  readonly tm_hash1: (x: number, seed: number) => number;
  readonly tm_hash2: (x: number, y: number, seed: number) => number;
  readonly tm_hash3: (x: number, y: number, z: number, seed: number) => number;
  readonly tm_hash_to_unit: (h: number) => number;
  readonly tm_hash_to_signed: (h: number) => number;

  readonly tm_tan_core: (x: number) => number;
  readonly tm_atan_core: (x: number) => number;
  readonly tm_tan_warp: (u: number) => number;
  readonly tm_atan_warp_inverse: (t: number) => number;
  readonly tm_rational_bump: (r2: number, k: number) => number;
  readonly tm_compact_falloff: (r: number) => number;
  readonly tm_tan_at_one: () => number;

  readonly tm_gradient_noise3: (x: number, y: number, z: number, seed: number) => number;
  readonly tm_billow_noise3: (x: number, y: number, z: number, seed: number) => number;
  readonly tm_ridged_noise3: (x: number, y: number, z: number, seed: number) => number;
  readonly tm_fbm3: (
    x: number,
    y: number,
    z: number,
    seed: number,
    octaves: number,
    frequency: number,
    amplitude: number,
    lacunarity: number,
    gain: number,
  ) => number;
  readonly tm_fbm_normalisation: (octaves: number, amplitude: number, gain: number) => number;
  readonly tm_octave_rotations: (out: number) => number;

  readonly tm_sfc32_new: (s0: number, s1: number, s2: number, s3: number) => number;
  readonly tm_tile_rng: (hi: number, lo: number, tileId: number, layer: number) => number;
  readonly tm_sfc32_free: (h: number) => void;
  readonly tm_sfc32_next_u32: (h: number) => number;
  readonly tm_sfc32_next_unit: (h: number) => number;
  readonly tm_sfc32_next_range: (h: number, lo: number, hi: number) => number;
  readonly tm_sfc32_next_below: (h: number, bound: number) => number;
  readonly tm_stream_seed: (
    hi: number,
    lo: number,
    tileId: number,
    layer: number,
    out: number,
  ) => void;
  readonly tm_hash_seed_string: (ptr: number, len: number, out: number) => void;

  readonly tm_face_uv_to_direction: (face: number, u: number, v: number, out: number) => void;
  readonly tm_direction_to_face_uv: (x: number, y: number, z: number, out: number) => void;
  readonly tm_tile_vertex_directions: (
    face: number,
    u0: number,
    v0: number,
    size: number,
    n: number,
    out: number,
  ) => void;

  readonly tm_make_tile_id: (face: number, depth: number, quadPath: number) => number;
  readonly tm_tile_depth: (id: number) => number;
  readonly tm_tile_face: (id: number) => number;
  readonly tm_tile_quad_path: (id: number) => number;
  readonly tm_tile_parent: (id: number) => number;
  readonly tm_tile_child: (id: number, childIndex: number) => number;
  readonly tm_tile_bounds: (id: number, out: number) => void;

  readonly tm_generate_tile: (
    params: number,
    elevation: number,
    waterMask: number,
    materials: number,
    directions: number,
  ) => void;
}

/** An sfc32 stream living in WASM memory. Mirrors the `Sfc32` class. */
export interface WasmSfc32 {
  nextUint32(): number;
  nextUnit(): number;
  nextRange(lo: number, hi: number): number;
  nextBelow(bound: number): number;
  /** Release the handle. Streams are cheap but not free; long-lived callers should. */
  free(): void;
}

/** The WASM kernel, method-for-method with `packages/core/src/kernel`. */
export interface WasmKernel {
  readonly abiVersion: number;

  pow2(x: number): number;
  pow3(x: number): number;
  powi(x: number, n: number): number;
  clamp(x: number, lo: number, hi: number): number;
  lerp(a: number, b: number, t: number): number;
  smoothstep(t: number): number;
  smootherstep(t: number): number;

  mix32(x: number): number;
  hash1(x: number, seed: number): number;
  hash2(x: number, y: number, seed: number): number;
  hash3(x: number, y: number, z: number, seed: number): number;
  hashToUnit(h: number): number;
  hashToSigned(h: number): number;

  tanCore(x: number): number;
  atanCore(x: number): number;
  tanWarp(u: number): number;
  atanWarpInverse(t: number): number;
  rationalBump(r2: number, k: number): number;
  compactFalloff(r: number): number;
  /** `tan(π/4)` as the twin computes it — the seam guarantee's divisor. */
  tanAtOne(): number;

  gradientNoise3(x: number, y: number, z: number, seed: number): number;
  billowNoise3(x: number, y: number, z: number, seed: number): number;
  ridgedNoise3(x: number, y: number, z: number, seed: number): number;
  fbm3(x: number, y: number, z: number, seed: number, params: FbmParams): number;
  fbmNormalisation(params: FbmParams): number;
  /** Copy of the crate's octave rotation table, for direct comparison. */
  octaveRotations(): Float64Array;

  newSfc32(s0: number, s1: number, s2: number, s3: number): WasmSfc32;
  tileRng(hi: number, lo: number, tileId: number, layer: number): WasmSfc32;
  streamSeed(hi: number, lo: number, tileId: number, layer: number): Uint32Array;
  hashSeedString(seed: string): Uint32Array;

  faceUvToDirection(face: number, u: number, v: number): Direction;
  directionToFaceUv(d: Direction): FaceUv;
  tileVertexDirections(
    face: number,
    u0: number,
    v0: number,
    size: number,
    n: number,
    out: Float64Array,
  ): void;

  makeTileId(face: number, depth: number, quadPath: number): number;
  tileDepth(id: number): number;
  tileFace(id: number): number;
  tileQuadPath(id: number): number;
  tileParent(id: number): number;
  tileChild(id: number, childIndex: number): number;
  tileBounds(id: number): { u0: number; v0: number; size: number };

  generateTile(input: TileGenInput, out: TileGenOutput): void;
}

/** Bytes of scratch space for small out-parameters. Ample: the largest is 216 doubles. */
const SCRATCH_BYTES = 2048;

/**
 * Instantiate the kernel from raw module bytes.
 *
 * Takes bytes rather than a path or URL so the same function serves Node, the
 * browser verify page and a worker. The caller decides how to fetch them.
 *
 * The module imports nothing, so there is no import object and nothing a host
 * could accidentally vary between platforms.
 */
export async function instantiateWasmKernel(
  bytes: ArrayBuffer | ArrayBufferView,
): Promise<WasmKernel> {
  const host = (globalThis as { WebAssembly?: WasmHost }).WebAssembly;
  if (host === undefined) {
    throw new Error('this host has no WebAssembly support; the WASM kernel cannot be loaded');
  }
  const { instance } = await host.instantiate(bytes, {});
  return wrapWasmKernel(instance);
}

/** Wrap an already-instantiated module. */
export function wrapWasmKernel(instance: WasmInstanceLike): WasmKernel {
  const raw = instance.exports as unknown as RawExports;

  const abiVersion = raw.tm_abi_version();
  if (abiVersion !== EXPECTED_ABI_VERSION) {
    // A stale .wasm in a build directory otherwise loads happily and fails the
    // parity battery, which reads as a determinism bug rather than as the build
    // problem it is.
    throw new Error(
      `WASM kernel ABI ${abiVersion}, binding expects ${EXPECTED_ABI_VERSION}. ` +
        'Rebuild the crate: pnpm wasm:build',
    );
  }

  // Memory views must be re-derived after any allocation: growing the WASM
  // memory replaces the backing ArrayBuffer and detaches every existing view.
  // Caching them and forgetting this produces a TypeError at best and reads
  // from a dead buffer at worst.
  let cachedBuffer: ArrayBufferLike | undefined;
  let f64: Float64Array;
  let u32: Uint32Array;
  let u16: Uint16Array;
  let u8: Uint8Array;

  function refresh(): void {
    const buf = raw.memory.buffer;
    if (buf !== cachedBuffer) {
      cachedBuffer = buf;
      f64 = new Float64Array(buf);
      u32 = new Uint32Array(buf);
      u16 = new Uint16Array(buf);
      u8 = new Uint8Array(buf);
    }
  }

  function alloc(size: number): number {
    const ptr = raw.tm_alloc(size);
    if (ptr === 0) {
      throw new Error(`WASM kernel could not allocate ${size} bytes`);
    }
    refresh();
    return ptr;
  }

  const scratch = alloc(SCRATCH_BYTES);
  refresh();

  /** Lazily grown staging block, for anything larger than the scratch space. */
  let staging = { ptr: 0, bytes: 0 };
  function stagingPtr(bytes: number): number {
    if (bytes > staging.bytes) {
      if (staging.ptr !== 0) {
        raw.tm_free(staging.ptr, staging.bytes);
      }
      // Round up so a sweep over growing sizes does not reallocate every step.
      const want = Math.max(bytes, staging.bytes * 2, 4096);
      staging = { ptr: alloc(want), bytes: want };
    }
    return staging.ptr;
  }

  function makeStream(handle: number): WasmSfc32 {
    let live = handle;
    return {
      // WASM i32 returns arrive in JavaScript sign-extended; `>>> 0` restores
      // the unsigned reading the TypeScript kernel produces.
      nextUint32: () => raw.tm_sfc32_next_u32(live) >>> 0,
      nextUnit: () => raw.tm_sfc32_next_unit(live),
      nextRange: (lo, hi) => raw.tm_sfc32_next_range(live, lo, hi),
      nextBelow: (bound) => raw.tm_sfc32_next_below(live, bound) >>> 0,
      free: () => {
        if (live !== 0) {
          raw.tm_sfc32_free(live);
          live = 0;
        }
      },
    };
  }

  return {
    abiVersion,

    pow2: raw.tm_pow2,
    pow3: raw.tm_pow3,
    powi: raw.tm_powi,
    clamp: raw.tm_clamp,
    lerp: raw.tm_lerp,
    smoothstep: raw.tm_smoothstep,
    smootherstep: raw.tm_smootherstep,

    mix32: (x) => raw.tm_mix32(x) >>> 0,
    hash1: (x, seed) => raw.tm_hash1(x, seed) >>> 0,
    hash2: (x, y, seed) => raw.tm_hash2(x, y, seed) >>> 0,
    hash3: (x, y, z, seed) => raw.tm_hash3(x, y, z, seed) >>> 0,
    hashToUnit: raw.tm_hash_to_unit,
    hashToSigned: raw.tm_hash_to_signed,

    tanCore: raw.tm_tan_core,
    atanCore: raw.tm_atan_core,
    tanWarp: raw.tm_tan_warp,
    atanWarpInverse: raw.tm_atan_warp_inverse,
    rationalBump: raw.tm_rational_bump,
    compactFalloff: raw.tm_compact_falloff,
    tanAtOne: raw.tm_tan_at_one,

    gradientNoise3: raw.tm_gradient_noise3,
    billowNoise3: raw.tm_billow_noise3,
    ridgedNoise3: raw.tm_ridged_noise3,

    fbm3(x, y, z, seed, params) {
      return raw.tm_fbm3(
        x,
        y,
        z,
        seed,
        params.octaves,
        params.frequency,
        params.amplitude,
        params.lacunarity,
        params.gain,
      );
    },

    fbmNormalisation(params) {
      return raw.tm_fbm_normalisation(params.octaves, params.amplitude, params.gain);
    },

    octaveRotations() {
      refresh();
      const count = raw.tm_octave_rotations(scratch);
      const base = scratch / 8;
      return f64.slice(base, base + count);
    },

    newSfc32: (s0, s1, s2, s3) => makeStream(raw.tm_sfc32_new(s0, s1, s2, s3)),
    tileRng: (hi, lo, tileId, layer) => makeStream(raw.tm_tile_rng(hi, lo, tileId, layer)),

    streamSeed(hi, lo, tileId, layer) {
      refresh();
      raw.tm_stream_seed(hi, lo, tileId, layer, scratch);
      const base = scratch / 4;
      return u32.slice(base, base + 4);
    },

    hashSeedString(seed) {
      // UTF-16 code units, matching the TypeScript's `charCodeAt` walk. A
      // TextEncoder would produce UTF-8 and hash astral characters differently.
      const bytes = seed.length * 2;
      const ptr = bytes <= SCRATCH_BYTES - 16 ? scratch + 16 : stagingPtr(bytes);
      refresh();
      const base = ptr / 2;
      for (let i = 0; i < seed.length; i++) {
        u16[base + i] = seed.charCodeAt(i);
      }
      raw.tm_hash_seed_string(ptr, seed.length, scratch);
      const out = scratch / 4;
      return u32.slice(out, out + 2);
    },

    faceUvToDirection(face, u, v) {
      refresh();
      raw.tm_face_uv_to_direction(face, u, v, scratch);
      const base = scratch / 8;
      return { x: f64[base]!, y: f64[base + 1]!, z: f64[base + 2]! };
    },

    directionToFaceUv(d) {
      refresh();
      raw.tm_direction_to_face_uv(d.x, d.y, d.z, scratch);
      const base = scratch / 8;
      return { face: f64[base]!, u: f64[base + 1]!, v: f64[base + 2]! };
    },

    tileVertexDirections(face, u0, v0, size, n, out) {
      const needed = 3 * (n + 1) * (n + 1);
      if (out.length < needed) {
        throw new RangeError(`out buffer holds ${out.length}, needs ${needed}`);
      }
      const ptr = stagingPtr(needed * 8);
      refresh();
      raw.tm_tile_vertex_directions(face, u0, v0, size, n, ptr);
      refresh();
      out.set(f64.subarray(ptr / 8, ptr / 8 + needed));
    },

    makeTileId: raw.tm_make_tile_id,
    tileDepth: raw.tm_tile_depth,
    tileFace: raw.tm_tile_face,
    tileQuadPath: raw.tm_tile_quad_path,
    tileParent: raw.tm_tile_parent,
    tileChild: raw.tm_tile_child,

    tileBounds(id) {
      refresh();
      raw.tm_tile_bounds(id, scratch);
      const base = scratch / 8;
      return { u0: f64[base]!, v0: f64[base + 1]!, size: f64[base + 2]! };
    },

    generateTile(input, out) {
      const { n } = input;
      const count = (n + 1) * (n + 1);
      if (out.elevation.length < count || out.materials.length < count) {
        throw new RangeError(`output buffers hold too few elements for n=${n}`);
      }

      // One block for the parameters and all four output buffers, so a tile
      // costs a single allocation. Offsets are 8-aligned where doubles land.
      const paramBytes = TILE_PARAM_COUNT * 8;
      const elevBytes = count * 8;
      const dirBytes = count * 3 * 8;
      const maskBytes = count;
      // Round the byte buffers up to a multiple of 8 so `directions` stays aligned.
      const maskBlock = (maskBytes + 7) & ~7;

      const total = paramBytes + elevBytes + dirBytes + maskBlock * 2;
      const base = stagingPtr(total);
      refresh();

      const pParams = base;
      const pElev = pParams + paramBytes;
      const pDir = pElev + elevBytes;
      const pWater = pDir + dirBytes;
      const pMat = pWater + maskBlock;

      const p = pParams / 8;
      f64[p] = input.face;
      f64[p + 1] = input.u0;
      f64[p + 2] = input.v0;
      f64[p + 3] = input.size;
      f64[p + 4] = n;
      f64[p + 5] = input.seedHi;
      f64[p + 6] = input.seedLo;
      f64[p + 7] = input.tileId;
      f64[p + 8] = input.fbm.octaves;
      f64[p + 9] = input.fbm.frequency;
      f64[p + 10] = input.fbm.amplitude;
      f64[p + 11] = input.fbm.lacunarity;
      f64[p + 12] = input.fbm.gain;
      f64[p + 13] = input.amplitudeM;

      raw.tm_generate_tile(pParams, pElev, pWater, pMat, pDir);
      refresh();

      out.elevation.set(f64.subarray(pElev / 8, pElev / 8 + count));
      out.directions.set(f64.subarray(pDir / 8, pDir / 8 + count * 3));
      out.waterMask.set(u8.subarray(pWater, pWater + count));
      out.materials.set(u8.subarray(pMat, pMat + count));
    },
  };
}
